#!/usr/bin/env python3
"""
anki_sync.py — Sync flashcards between bing-study vault and AnkiWeb.

Card CONTENT is generated by the agent during sessions (ingest, quiz, learn)
and stored in each note's frontmatter ``anki_cards`` field.  This script
handles SYNC: pushing those cards to Anki and pulling review progress back.

Usage:
    python scripts/anki_sync.py sync     # full bidirectional
    python scripts/anki_sync.py push     # repo → local Anki collection
    python scripts/anki_sync.py pull     # Anki progress → repo mastery
    python scripts/anki_sync.py status   # show sync status (no changes)

Environment:
    ANKIWEB_USER   AnkiWeb email      (required on first sync)
    ANKIWEB_PASS   AnkiWeb password   (required on first sync; host key cached after)
    FASTANKI_DIR   Override data dir  (default: ~/.fastanki)

Dependencies:
    pip install fastanki pyyaml
"""

from __future__ import annotations

import os
import re
import sys
import time
from datetime import date
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

VAULT = Path(__file__).resolve().parent.parent

DECK_PREFIX = "BingStudy"
KNOWLEDGE_DIRS = {"ontology", "philosophy", "history", "ai"}

OUR_TAG = "bingstudy"            # applied to every card we create
SUSPEND_MASTERY = 0.9            # suspend Anki cards when mastery >= this
MAX_ANKI_BOOST = 0.2             # ceiling for mastery boost from Anki data
FULL_MEMORY_IVL = 90             # interval (days) scored as 1.0

# ---------------------------------------------------------------------------
# Optional .env
# ---------------------------------------------------------------------------

try:
    from dotenv import load_dotenv
    load_dotenv(VAULT / ".env")
except ImportError:
    pass

# ---------------------------------------------------------------------------
# Frontmatter I/O
# ---------------------------------------------------------------------------

_FM_PAT = re.compile(r"\A---\n(.+?\n)---\n(.*)", re.DOTALL)


def parse_note(path: Path) -> tuple[dict | None, str]:
    """Return (frontmatter, body).  ``None`` frontmatter when file is not a note."""
    text = path.read_text("utf-8")
    m = _FM_PAT.match(text)
    if not m:
        return None, text
    return yaml.safe_load(m.group(1)), m.group(2)


def write_note(path: Path, fm: dict, body: str) -> None:
    """Rewrite note with updated frontmatter; body is preserved byte-for-byte."""
    yml = yaml.dump(fm, default_flow_style=False, allow_unicode=True,
                    sort_keys=False, width=120)
    path.write_text(f"---\n{yml}---\n{body}", "utf-8")


def scan_vault() -> list[tuple[Path, dict, str]]:
    """Every knowledge-point note in the vault (has ``domain`` + ``mastery``)."""
    results: list[tuple[Path, dict, str]] = []
    for d in sorted(VAULT.iterdir()):
        if not d.is_dir() or d.name not in KNOWLEDGE_DIRS:
            continue
        for md in sorted(d.rglob("*.md")):
            if "/assets/" in str(md) or md.name.startswith("."):
                continue
            fm, body = parse_note(md)
            if fm and "domain" in fm and "mastery" in fm:
                results.append((md, fm, body))
    return results


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def deck_for(domain: str) -> str:
    return f"{DECK_PREFIX}::{domain.capitalize()}"


def _ensure_tag(tags: list | None, tag: str) -> list:
    tags = list(tags or [])
    if tag not in tags:
        tags.insert(0, tag)
    return tags


# ---------------------------------------------------------------------------
# Push: repo → Anki collection
# ---------------------------------------------------------------------------

def push_cards(col, notes: list, *, dry_run: bool = False) -> dict:
    """Create / update / suspend-toggle cards.  Returns stats dict."""
    stats = {"created": 0, "updated": 0, "suspended": 0, "unsuspended": 0}

    for path, fm, body in notes:
        cards: list[dict] = fm.get("anki_cards") or []
        if not cards:
            continue

        deck = deck_for(fm.get("domain", "ontology"))
        mastery = float(fm.get("mastery", 0))
        file_dirty = False

        for card in cards:
            nid = card.get("anki_note_id")
            ctype = card.get("type", "basic")
            tags = _ensure_tag(card.get("tags"), OUR_TAG)

            # ---- create new card ----
            if not nid:
                if dry_run:
                    label = (card.get("front") or card.get("text") or "?")[:60]
                    print(f"  + [{ctype}] {label}")
                    stats["created"] += 1
                    continue

                note_obj = _create_note(col, card, ctype, deck, tags)
                card["anki_note_id"] = note_obj.id
                nid = note_obj.id
                file_dirty = True
                stats["created"] += 1

            # ---- update existing card ----
            else:
                if dry_run:
                    continue
                try:
                    anki_note = col.get_note(nid)
                    if _content_differs(anki_note, card, ctype):
                        _update_content(col, nid, card, ctype)
                        stats["updated"] += 1
                except KeyError:
                    # deleted in Anki → recreate
                    note_obj = _create_note(col, card, ctype, deck, tags)
                    card["anki_note_id"] = note_obj.id
                    nid = note_obj.id
                    file_dirty = True
                    stats["created"] += 1

            # ---- suspend / unsuspend by mastery ----
            if not dry_run and nid:
                s, u = _toggle_suspend(col, nid, mastery)
                stats["suspended"] += s
                stats["unsuspended"] += u

        if file_dirty:
            write_note(path, fm, body)

    if not dry_run:
        col._dirty()
    return stats


def _create_note(col, card: dict, ctype: str, deck: str, tags: list):
    if ctype == "cloze":
        kw = {"Text": card["text"]}
        if card.get("back_extra"):
            kw["Back Extra"] = card["back_extra"]
        return col.add(model="Cloze", deck=deck, tags=tags, **kw)
    return col.add(deck=deck, tags=tags, Front=card["front"], Back=card["back"])


def _content_differs(anki_note, card: dict, ctype: str) -> bool:
    if ctype == "cloze":
        return anki_note["Text"] != card.get("text", "")
    return (anki_note["Front"] != card.get("front", "")
            or anki_note["Back"] != card.get("back", ""))


def _update_content(col, nid: int, card: dict, ctype: str):
    if ctype == "cloze":
        col.update_note(nid, Text=card["text"])
    else:
        col.update_note(nid, Front=card["front"], Back=card["back"])


def _toggle_suspend(col, nid: int, mastery: float) -> tuple[int, int]:
    """Returns (suspended_count, unsuspended_count)."""
    now_ts = int(time.time())
    suspended = unsuspended = 0
    for (cid, queue, ctype_db) in col.q(
            "select id, queue, type from cards where nid=?", nid):
        if mastery >= SUSPEND_MASTERY and queue != -1:
            col.con.execute(
                "update cards set queue=-1, mod=?, usn=-1 where id=?",
                (now_ts, cid))
            suspended += 1
        elif mastery < SUSPEND_MASTERY and queue == -1:
            # unsuspend: restore queue to card type
            col.con.execute(
                "update cards set queue=?, mod=?, usn=-1 where id=?",
                (ctype_db, now_ts, cid))
            unsuspended += 1
    return suspended, unsuspended


# ---------------------------------------------------------------------------
# Orphan detection: cards in Anki but source note removed from repo
# ---------------------------------------------------------------------------

def handle_orphans(col, notes: list, *, dry_run: bool = False) -> int:
    """Suspend Anki cards whose source note no longer exists.  Returns count."""
    repo_nids: set[int] = set()
    for _, fm, _ in notes:
        for c in fm.get("anki_cards") or []:
            if nid := c.get("anki_note_id"):
                repo_nids.add(nid)

    anki_notes = col.find_notes(tag=OUR_TAG)
    count = 0
    now_ts = int(time.time())

    for note in anki_notes:
        if note.id in repo_nids:
            continue
        if dry_run:
            flds = " | ".join(f"{k}={v[:30]}" for k, v in note.fields.items())
            print(f"  ⏸ orphan: {flds}")
        else:
            for (cid, queue) in col.q(
                    "select id, queue from cards where nid=?", note.id):
                if queue != -1:
                    col.con.execute(
                        "update cards set queue=-1, mod=?, usn=-1 where id=?",
                        (now_ts, cid))
        count += 1

    if not dry_run and count:
        col._dirty()
    return count


# ---------------------------------------------------------------------------
# Pull: Anki collection → repo mastery boost
# ---------------------------------------------------------------------------

def pull_progress(col, notes: list, *, dry_run: bool = False) -> dict:
    """Read Anki intervals; conservatively boost repo mastery.

    Boost logic:
      memory_score = avg(min(ivl, 90) / 90) across non-suspended cards
      anki_boost   = min(0.2, memory_score × 0.2)
      delta        = anki_boost − previous_boost   (only positive)
      mastery     += delta

    Anki progress only ADDS to mastery, never decreases it.
    """
    stats = {"boosted": 0, "cards_read": 0}

    for path, fm, body in notes:
        cards: list[dict] = fm.get("anki_cards") or []
        nids = [c["anki_note_id"] for c in cards if c.get("anki_note_id")]
        if not nids:
            continue

        # Gather intervals from non-suspended cards
        intervals: list[int] = []
        for nid in nids:
            for (ivl,) in col.q(
                    "select ivl from cards where nid=? and queue != -1", nid):
                intervals.append(ivl)
                stats["cards_read"] += 1

        if not intervals:
            continue

        mem = sum(min(ivl, FULL_MEMORY_IVL) / FULL_MEMORY_IVL
                  for ivl in intervals) / len(intervals)
        boost = min(MAX_ANKI_BOOST, mem * MAX_ANKI_BOOST)
        prev_boost = float(fm.get("anki_mastery_boost", 0))

        if boost <= prev_boost:
            continue

        delta = round(boost - prev_boost, 3)
        cur = float(fm.get("mastery", 0))
        new_mastery = round(min(1.0, cur + delta), 2)
        title = fm.get("title", path.stem)

        if dry_run:
            print(f"  📈 {title}: mastery {cur} → {new_mastery} "
                  f"(anki +{delta:.3f})")
        else:
            fm["mastery"] = new_mastery
            fm["anki_mastery_boost"] = round(boost, 3)
            fm["modified"] = date.today().isoformat()
            write_note(path, fm, body)

        stats["boosted"] += 1

    return stats


# ---------------------------------------------------------------------------
# AnkiWeb sync
# ---------------------------------------------------------------------------

def sync_ankiweb() -> None:
    from fastanki import sync as _sync
    user = os.environ.get("ANKIWEB_USER")
    passw = os.environ.get("ANKIWEB_PASS")
    kw = {"user": user, "passw": passw} if user and passw else {}
    try:
        _sync(**kw)
    except Exception as exc:
        if "empty" in str(exc).lower() and "upload" in str(exc).lower():
            print("   (first sync: uploading local collection to AnkiWeb)")
            _sync(upload=True, **kw)
        else:
            raise


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_sync():
    from fastanki import Collection

    print("🔄 Syncing with AnkiWeb (download)…")
    sync_ankiweb()

    notes = scan_vault()
    print(f"📂 Found {len(notes)} knowledge-point notes\n")

    col = Collection.open()
    try:
        print("⬇️  Pulling Anki progress…")
        ps = pull_progress(col, notes)
        print(f"   Boosted {ps['boosted']} notes "
              f"({ps['cards_read']} cards read)")

        # Re-scan: mastery may have changed → affects suspend decisions
        notes = scan_vault()

        print("\n⬆️  Pushing cards…")
        xs = push_cards(col, notes)
        print(f"   Created {xs['created']}, updated {xs['updated']}")
        if xs["suspended"] or xs["unsuspended"]:
            print(f"   Suspended {xs['suspended']}, "
                  f"unsuspended {xs['unsuspended']}")

        orphans = handle_orphans(col, notes)
        if orphans:
            print(f"   ⏸ Suspended {orphans} orphan card(s)")
    finally:
        col.close()

    print("\n🔄 Syncing with AnkiWeb (upload)…")
    sync_ankiweb()
    print("\n✅ Done!")


def cmd_push():
    from fastanki import Collection
    notes = scan_vault()
    print(f"📂 {len(notes)} notes\n")
    col = Collection.open()
    try:
        s = push_cards(col, notes)
        o = handle_orphans(col, notes)
    finally:
        col.close()
    print(f"Created {s['created']}, updated {s['updated']}, "
          f"suspended {s['suspended']}, unsuspended {s['unsuspended']}")
    if o:
        print(f"⏸ {o} orphan(s) suspended")


def cmd_pull():
    from fastanki import Collection
    notes = scan_vault()
    col = Collection.open()
    try:
        s = pull_progress(col, notes)
    finally:
        col.close()
    print(f"Boosted {s['boosted']} notes ({s['cards_read']} cards)")


def cmd_status():
    notes = scan_vault()
    total = synced = pending = no_cards = 0
    print(f"📂 {len(notes)} knowledge-point notes\n")
    for path, fm, _ in notes:
        cards: list[dict] = fm.get("anki_cards") or []
        title = fm.get("title", path.stem)
        mastery = fm.get("mastery", 0)
        if not cards:
            print(f"  ⚪ {title} (mastery={mastery}) — no cards")
            no_cards += 1
            continue
        s = sum(1 for c in cards if c.get("anki_note_id"))
        p = len(cards) - s
        total += len(cards)
        synced += s
        pending += p
        icon = "✅" if p == 0 else "⏳"
        print(f"  {icon} {title} (mastery={mastery}) — "
              f"{len(cards)} cards ({s} synced, {p} pending)")
    print(f"\nTotal: {total} cards, {synced} synced, "
          f"{pending} pending, {no_cards} notes without cards")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

COMMANDS = {
    "sync": cmd_sync,
    "push": cmd_push,
    "pull": cmd_pull,
    "status": cmd_status,
}


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
        print(__doc__.strip())
        sys.exit(0 if len(sys.argv) < 2 else 1)
    try:
        COMMANDS[sys.argv[1]]()
    except ImportError as exc:
        if "fastanki" in str(exc):
            print("❌ fastanki not installed.  Run: pip install fastanki",
                  file=sys.stderr)
            sys.exit(1)
        raise
    except Exception as exc:
        print(f"❌ {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
